# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmaterial',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outmaterial',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outmaterial',
            name='usage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
