# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20161020_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['create_time']},
        ),
    ]
