# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20161020_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'get_latest_by': 'create_time', 'ordering': ['create_time']},
        ),
        migrations.AlterField(
            model_name='material',
            name='count',
            field=models.IntegerField(default=0, verbose_name='\u8ba1\u6570'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u6750\u6599\u540d'),
        ),
        migrations.AlterField(
            model_name='material',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u4ef7\u683c'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type_no',
            field=models.CharField(max_length=50, verbose_name='\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='\u5355\u4f4d'),
        ),
    ]
